services:
  skeleton-app:
    image: node:24.15.0-slim
    ports:
      - 5173:5173
    working_dir: /app
    environment:
      LOCAL_API_BASE_URL: "https://multi-ai-gateway.okmethod2020.workers.dev"
      VITE_DEFAULT_LLM_PROVIDER: "groq"
    volumes:
      - ./apps/skeleton-app:/app
      - skeleton-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

volumes:
  skeleton-app-node-modules:
