services:
  skeleton-app:
    depends_on:
      - fast-api-server
    image: node:24.15.0-slim
    ports:
      - 5173:5173
    working_dir: /app
    environment:
      VITE_API_BASE_URL: "http://fast-api-server:8000"
    volumes:
      - ./apps/skeleton-app:/app
      - skeleton-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"
  
  fast-api-server:
    build:
      context: ./apps/fast-api-server
      target: development
      args:
        PYTHON_VERSION: 3.13.2
    ports:
      - 8000:8000
    environment:
      GOOGLE_CLOUD_PROJECT: emulator
    volumes:
      - ./apps/fast-api-server:/app
      - fast-api-server-venv:/app/.venv
    command:
      ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--log-config", "src/logging.ini", "--reload"]
    tty: true

volumes:
  skeleton-app-node-modules:
  fast-api-server-venv:
