import { TypeName } from "$lib/types/type";
import type { TypeData } from "$lib/types/type";

export const TYPE_COLOR_DICT: Record<TypeName, string> = {
  normal: "#FDF6CB",
  fighting: "#EE8130",
  flying: "#A2C3E8",
  poison: "#A33EA1",
  ground: "#9C7743",
  rock: "#C0B88A",
  bug: "#A6B91A",
  ghost: "#735797",
  steel: "#B7B7CE",
  fire: "#D22E28",
  water: "#5285C6",
  grass: "#7AC74C",
  electric: "#F7D02C",
  psychic: "#F95587",
  ice: "#6DC8EB",
  dragon: "#545BA8",
  dark: "#222222",
  fairy: "#FCAFF9",
  unknown: "#888888",
};

// jsonファイルからコピー後、" as TypeName" を書き足した
export const STATIC_TYPE_DICT: Record<TypeName, TypeData> = {
  normal: {
    id: 1,
    enName: "normal" as TypeName,
    jaName: "ノーマル",
    damageRelations: {
      doubleDamageFrom: ["fighting"] as TypeName[],
      doubleDamageTo: [] as TypeName[],
      halfDamageFrom: [] as TypeName[],
      halfDamageTo: ["rock", "steel"] as TypeName[],
      noDamageFrom: ["ghost"] as TypeName[],
      noDamageTo: ["ghost"] as TypeName[],
    },
  },
  fighting: {
    id: 2,
    enName: "fighting" as TypeName,
    jaName: "かくとう",
    damageRelations: {
      doubleDamageFrom: ["flying", "psychic", "fairy"] as TypeName[],
      doubleDamageTo: ["normal", "rock", "steel", "ice", "dark"] as TypeName[],
      halfDamageFrom: ["rock", "bug", "dark"] as TypeName[],
      halfDamageTo: ["flying", "poison", "bug", "psychic", "fairy"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: ["ghost"] as TypeName[],
    },
  },
  flying: {
    id: 3,
    enName: "flying" as TypeName,
    jaName: "ひこう",
    damageRelations: {
      doubleDamageFrom: ["rock", "electric", "ice"] as TypeName[],
      doubleDamageTo: ["fighting", "bug", "grass"] as TypeName[],
      halfDamageFrom: ["fighting", "bug", "grass"] as TypeName[],
      halfDamageTo: ["rock", "steel", "electric"] as TypeName[],
      noDamageFrom: ["ground"] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  poison: {
    id: 4,
    enName: "poison" as TypeName,
    jaName: "どく",
    damageRelations: {
      doubleDamageFrom: ["ground", "psychic"] as TypeName[],
      doubleDamageTo: ["grass", "fairy"] as TypeName[],
      halfDamageFrom: ["fighting", "poison", "bug", "grass", "fairy"] as TypeName[],
      halfDamageTo: ["poison", "ground", "rock", "ghost"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: ["steel"] as TypeName[],
    },
  },
  ground: {
    id: 5,
    enName: "ground" as TypeName,
    jaName: "じめん",
    damageRelations: {
      doubleDamageFrom: ["water", "grass", "ice"] as TypeName[],
      doubleDamageTo: ["poison", "rock", "steel", "fire", "electric"] as TypeName[],
      halfDamageFrom: ["poison", "rock"] as TypeName[],
      halfDamageTo: ["bug", "grass"] as TypeName[],
      noDamageFrom: ["electric"] as TypeName[],
      noDamageTo: ["flying"] as TypeName[],
    },
  },

  rock: {
    id: 6,
    enName: "rock" as TypeName,
    jaName: "いわ",
    damageRelations: {
      doubleDamageFrom: ["fighting", "ground", "steel", "water", "grass"] as TypeName[],
      doubleDamageTo: ["flying", "bug", "fire", "ice"] as TypeName[],
      halfDamageFrom: ["normal", "flying", "poison", "fire"] as TypeName[],
      halfDamageTo: ["fighting", "ground", "steel"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },

  bug: {
    id: 7,
    enName: "bug" as TypeName,
    jaName: "むし",
    damageRelations: {
      doubleDamageFrom: ["flying", "rock", "fire"] as TypeName[],
      doubleDamageTo: ["grass", "psychic", "dark"] as TypeName[],
      halfDamageFrom: ["fighting", "ground", "grass"] as TypeName[],
      halfDamageTo: ["fighting", "flying", "poison", "ghost", "steel", "fire", "fairy"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  ghost: {
    id: 8,
    enName: "ghost" as TypeName,
    jaName: "ゴースト",
    damageRelations: {
      doubleDamageFrom: ["ghost", "dark"] as TypeName[],
      doubleDamageTo: ["ghost", "psychic"] as TypeName[],
      halfDamageFrom: ["poison", "bug"] as TypeName[],
      halfDamageTo: ["dark"] as TypeName[],
      noDamageFrom: ["normal", "fighting"] as TypeName[],
      noDamageTo: ["normal"] as TypeName[],
    },
  },
  steel: {
    id: 9,
    enName: "steel" as TypeName,
    jaName: "はがね",
    damageRelations: {
      doubleDamageFrom: ["fighting", "ground", "fire"] as TypeName[],
      doubleDamageTo: ["rock", "ice", "fairy"] as TypeName[],
      halfDamageFrom: [
        "normal",
        "flying",
        "rock",
        "bug",
        "steel",
        "grass",
        "psychic",
        "ice",
        "dragon",
        "fairy",
      ] as TypeName[],
      halfDamageTo: ["steel", "fire", "water", "electric"] as TypeName[],
      noDamageFrom: ["poison"] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  fire: {
    id: 10,
    enName: "fire" as TypeName,
    jaName: "ほのお",
    damageRelations: {
      doubleDamageFrom: ["ground", "rock", "water"] as TypeName[],
      doubleDamageTo: ["bug", "steel", "grass", "ice"] as TypeName[],
      halfDamageFrom: ["bug", "steel", "fire", "grass", "ice", "fairy"] as TypeName[],
      halfDamageTo: ["rock", "fire", "water", "dragon"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  water: {
    id: 11,
    enName: "water" as TypeName,
    jaName: "みず",
    damageRelations: {
      doubleDamageFrom: ["grass", "electric"] as TypeName[],
      doubleDamageTo: ["ground", "rock", "fire"] as TypeName[],
      halfDamageFrom: ["steel", "fire", "water", "ice"] as TypeName[],
      halfDamageTo: ["water", "grass", "dragon"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  grass: {
    id: 12,
    enName: "grass" as TypeName,
    jaName: "くさ",
    damageRelations: {
      doubleDamageFrom: ["flying", "poison", "bug", "fire", "ice"] as TypeName[],
      doubleDamageTo: ["ground", "rock", "water"] as TypeName[],
      halfDamageFrom: ["ground", "water", "grass", "electric"] as TypeName[],
      halfDamageTo: ["flying", "poison", "bug", "steel", "fire", "grass", "dragon"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  electric: {
    id: 13,
    enName: "electric" as TypeName,
    jaName: "でんき",
    damageRelations: {
      doubleDamageFrom: ["ground"] as TypeName[],
      doubleDamageTo: ["flying", "water"] as TypeName[],
      halfDamageFrom: ["flying", "steel", "electric"] as TypeName[],
      halfDamageTo: ["grass", "electric", "dragon"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: ["ground"] as TypeName[],
    },
  },
  psychic: {
    id: 14,
    enName: "psychic" as TypeName,
    jaName: "エスパー",
    damageRelations: {
      doubleDamageFrom: ["bug", "ghost", "dark"] as TypeName[],
      doubleDamageTo: ["fighting", "poison"] as TypeName[],
      halfDamageFrom: ["fighting", "psychic"] as TypeName[],
      halfDamageTo: ["steel", "psychic"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: ["dark"] as TypeName[],
    },
  },
  ice: {
    id: 15,
    enName: "ice" as TypeName,
    jaName: "こおり",
    damageRelations: {
      doubleDamageFrom: ["fighting", "rock", "steel", "fire"] as TypeName[],
      doubleDamageTo: ["flying", "ground", "grass", "dragon"] as TypeName[],
      halfDamageFrom: ["ice"] as TypeName[],
      halfDamageTo: ["steel", "fire", "water", "ice"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  dragon: {
    id: 16,
    enName: "dragon" as TypeName,
    jaName: "ドラゴン",
    damageRelations: {
      doubleDamageFrom: ["ice", "dragon", "fairy"] as TypeName[],
      doubleDamageTo: ["dragon"] as TypeName[],
      halfDamageFrom: ["fire", "water", "grass", "electric"] as TypeName[],
      halfDamageTo: ["steel"] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: ["fairy"] as TypeName[],
    },
  },
  dark: {
    id: 17,
    enName: "dark" as TypeName,
    jaName: "あく",
    damageRelations: {
      doubleDamageFrom: ["fighting", "bug", "fairy"] as TypeName[],
      doubleDamageTo: ["ghost", "psychic"] as TypeName[],
      halfDamageFrom: ["ghost", "dark"] as TypeName[],
      halfDamageTo: ["fighting", "dark", "fairy"] as TypeName[],
      noDamageFrom: ["psychic"] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  fairy: {
    id: 18,
    enName: "fairy" as TypeName,
    jaName: "フェアリー",
    damageRelations: {
      doubleDamageFrom: ["poison", "steel"] as TypeName[],
      doubleDamageTo: ["fighting", "dragon", "dark"] as TypeName[],
      halfDamageFrom: ["fighting", "bug", "dark"] as TypeName[],
      halfDamageTo: ["poison", "steel", "fire"] as TypeName[],
      noDamageFrom: ["dragon"] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
  unknown: {
    id: 10001,
    enName: "unknown" as TypeName,
    jaName: "？？？",
    damageRelations: {
      doubleDamageFrom: [] as TypeName[],
      doubleDamageTo: [] as TypeName[],
      halfDamageFrom: [] as TypeName[],
      halfDamageTo: [] as TypeName[],
      noDamageFrom: [] as TypeName[],
      noDamageTo: [] as TypeName[],
    },
  },
};
